### ISSUE TITLE
Remove Jython from the image?

### ISSUE THREAD

**Issue by frenzymadness** [fedora-python/fedora-python-tox#28]
Jython is basically not supported by tox/pip/pytest etc. and with every new release of those components, a new way it fails appears.

Do we want to keep it in the image and document that it has a limited support and tox (which is the main tool we use here) does not support it, or just remove it?

**Comment by hroncok** [comment]
I'd just remove it. It brings Java in and makes the entire thing needlessly large.

**Comment by frenzymadness** [comment]
Jython support removed.
