### ISSUE TITLE
Build the image cronly

### ISSUE THREAD

**Issue by hroncok** [fedora-python/fedora-python-tox#36]
When there are no changes in here, the Docker image can get a bit outdated. Would you consider building it weekly by cron?

**Comment by frenzymadness** [comment]
It would be nice to have but Docker hub doesn't seem to have this feature and "cascade build" feature was also removed :(

We can switch the responsibility to rebuild the image to Travis which should the make it cronly.

**Comment by hroncok** [comment]
> We can switch the responsibility to rebuild the image to Travis...

So currently, the images are not published on dockerhub by travis, but by some direct integration?

**Comment by frenzymadness** [comment]
> So currently, the images are not published on dockerhub by travis, but by some direct integration?

Yes, docker does a rebuild for every new commit.

**Comment by hroncok** [comment]
Understood :(

**Comment by frenzymadness** [comment]
So, in #37, I was able to delegate the responsibility to build and push the container image to Docker hub to Travis. But now it seems that I don't have full rights there to set up a cron build for fedora-python/fedora-python-tox on Travis-ci.org. I don't see the setting option in the hamburger menu which I see in my personal projects.

**Comment by hroncok** [comment]
You seem to  an Owner of fedora-python GH org :/

**Comment by hroncok** [comment]
Anyway, the travis job is already scheduled to run weekly. Let's see what happens in a week.

**Comment by frenzymadness** [comment]
The last commit in the master is seven days old and the last image build happened two days ago so it seems that Travis works well and we are done here. Thank you!

**Comment by hroncok** [comment]
Thank you!
