### ISSUE TITLE
Document and ensure that make is installed

### ISSUE THREAD

**Issue by encukou** [fedora-python/fedora-python-tox#43]
See: https://github.com/encukou/py3c/pull/39#discussion_r553461344

**Comment by frenzymadness** [comment]
Make is currently installed as a dependency of gcc and gcc is listed explicitly.

**Comment by hroncok** [comment]
Yes. The point here is to explicitly list make in the Dockerfile and README. The outcome is the same, but there is a certain guarantee for the users.
