### ISSUE TITLE
Support subdirectories

### ISSUE THREAD

**Issue by abompard** [fedora-python/fedora-python-tox#47]
I have multiple python packages in subdirectories in my repository, each having a `tox.ini` file. It would be useful to me if I could have `run_scripts.sh` cd to a subdirectory before running `tox`.

Related to https://github.com/fedora-python/tox-github-action/issues/16

**Comment by frenzymadness** [comment]
Feel free to open a PR.

**Comment by frenzymadness** [comment]
Could we use one of your projects in tests?

**Comment by abompard** [comment]
Sure! This could be a candidate: https://github.com/fedora-infra/datanommer
Sorry, I never got around to writing the PR. I had other things on my plate at that time and then forgot about it.

**Comment by frenzymadness** [comment]
The implementation is pretty simple but the testing of datanommer project isn't. The problem is that tests of the datanommer packages need a postgres database but the pg_ctl command cannot be run as root.
Do you have any simpler projects with tox.ini in a subdirectory?

**Comment by abompard** [comment]
Ah, right. I don't have any other that come to my mind right now (and are using tox), so I'll need to do some inventory.
Do all the tests in the container have to run as root?
