### ISSUE TITLE
Travis build is broken, image is outdated

### ISSUE THREAD

**Issue by hroncok** [fedora-python/fedora-python-tox#48]
The latest successful Travis build happened 3 months ago (with Python 3.10.0b1) and since June 15th, 2021, the building on travis-ci.org is ceased.

As a result, the Pythons are outdated:

My machine:

```
$ rpm -qa | grep -F python3. | sort
python3.10-3.10.0~rc1-1.fc33.x86_64
python3.5-3.5.10-5.fc33.x86_64
python3.6-3.6.14-1.fc33.x86_64
python3.7-3.7.11-1.fc33.x86_64
python3.8-3.8.11-1.fc33.x86_64
$ rpm -q python3
python3-3.9.6-2.fc33.x86_64
```

This image:

```
[root@9808fb7fd92c /]# rpm -qa | grep -F python3. | sort
python3.10-3.10.0~b1-1.fc33.x86_64
python3.5-3.5.10-5.fc33.x86_64
python3.6-3.6.13-1.fc33.x86_64
python3.7-3.7.10-1.fc33.x86_64
python3.8-3.8.10-1.fc33.x86_64
[root@9808fb7fd92c /]# rpm -q python3
python3-3.9.5-1.fc33.x86_64
```

The only up to date Python is Python 3.5, because it is EOL

**Comment by frenzymadness** [comment]
I've migrated the config to the new Travis instance and requested a new build but s390x has not started yet :disappointed: I'm also not sure whether the credit we have will be enough to rebuild the container every week so we might need to come up with some alternative. Do you know about any CI where we can run this job on all supported architectures?

**Comment by frenzymadness** [comment]
Btw, after the migration, logs of the previous builds are not available so I cannot investigate what was wrong.

**Comment by frenzymadness** [comment]
s390x job timed out, restarted.

**Comment by hroncok** [comment]
> Do you know about any CI where we can run this job on all supported architectures?

GitHub Actions? https://github.com/marketplace/actions/run-on-architecture

**Comment by hroncok** [comment]
https://blog.oddbit.com/post/2020-09-25-building-multi-architecture-im/

**Comment by frenzymadness** [comment]
So, after a few clicks here and there, the image is up-to-date again. I'm gonna closely watch the Travis cron job for a few weeks and if it won't be stable enough, we can try to migrate it to GH actions.

**Comment by hroncok** [comment]
```
[root@f6860924e023 /]# python3.6 --version
Python 3.6.14
[root@f6860924e023 /]# python3.7 --version
Python 3.7.11
[root@f6860924e023 /]# python3.8 --version
Python 3.8.11
[root@f6860924e023 /]# python3.9 --version
Python 3.9.6
[root@f6860924e023 /]# python3.10 --version
Python 3.10.0rc1
```

Awesome, thanks!

**Comment by frenzymadness** [comment]
All the images have been updated 13 hours ago.

**Comment by frenzymadness** [comment]
All images have been updated a day ago. One more week and I'll close this issue.

**Comment by frenzymadness** [comment]
The last update happened 21 hours ago, I think we are good to close this issue now.
