### ISSUE TITLE
Backward compatibility for Github Action

### ISSUE THREAD

**Issue by frenzymadness** [fedora-python/fedora-python-tox#56]
We have discussed this briefly with @encukou today. When we switch to F35, we might break someone's CI because F35 does not contain Python 3.5.

My idea is to build container images and create manifests with the fedora version in their name and release a new version of Github action every time we switch to a newer Fedora release.

We can build all the container images with the original tags like `amd64` and `amd64_fedora34`. The same applies to the latest manifest where we can use `latest` and `latest_fedora34`. We can then change the github action to use `latest_fedora34` explicitly. Then, when we switch to Fedora 35, the tags and manifests using `_fedora34` suffix will stay the same, and therefore the github action will stay stable and we can release a new version of the github action using `_fedora35`. Also, those who use the images directly can choose between a stable and possibly obsolete version of the images or rolling tags.

Does this make sense?

**Comment by hroncok** [comment]
It does.

**Comment by hroncok** [comment]
I have some questions.

 - Do we build e.g. Fedora 36 and 35 tags in parallel, offering the users to pick any Fedora version, or do we still only build one version (and the users can pick an older one, but not up to date)?
 - Do we add a warning to the EOLed tag in the last build we do?

**Comment by hroncok** [comment]
My idea was that we would regularly build both f35 and f36 tags (from different branches here maybe). Once Fedora 35 goes EOL, we would (potentially add a warning and) cancel the cron in that branch.

**Comment by hroncok** [comment]
And the GH action would be tagged to pull in that very image, so you could do `@f35`, `@f36`, etc.

**Comment by hroncok** [comment]
Keeping just the newest works for me. I was just trying to figure out what is the end goal here.
