### ISSUE TITLE
Moving the container to F37 or at least F36?

### ISSUE THREAD

**Issue by praiskup** [fedora-python/fedora-python-tox#60]
SSIA

**Comment by praiskup** [comment]
I thought I could test a pre-release Python 3.12 there, but that's not yet possible.  So no use-case => no problem => closing.  Sorry for the rush.

Seems like you are moving to Fedora N+1 when N goes EOL?  If so, just a small suggestion: it deserves a note in the README file that this is the policy.  Then nobody will be "shocked" the container is too old. :)

**Comment by hroncok** [comment]
> I thought I could test a pre-release Python 3.12 there, but that's not yet possible. 

See https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2137912 and https://src.fedoraproject.org/rpms/python3.11/pull-request/89

We plan to add it to Fedora 35 as well.

> Seems like you are moving to Fedora N+1 when N goes EOL? If so, just a small suggestion: it deserves a note in the README file that this is the policy. Then nobody will be "shocked" the container is too old. :)

https://github.com/fedora-python/fedora-python-tox/issues/61

**Comment by praiskup** [comment]
Thank you @hroncok !
