### ISSUE TITLE
tox 3 vs tox 4

### ISSUE THREAD

**Issue by hroncok** [fedora-python/fedora-python-tox#65]
Tox 4.0.0 was released. We need to decide what to do about that. Since this docker image uses stable Fedora, it will contain tox3 for a while. Should we document that and let it be? Should we package a conflicting version of tox4 into Fedora? etc.

**Comment by frenzymadness** [comment]
I'd keep a stable fedora with tox 3 until somebody asks for tox 4 explicitly.
